CRUDOperationsDemo/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("PayRollApp/", include("PayRollApp.urls")),
]

PayRollApp/urls.py
from django.urls import path

from PayRollApp import views

urlpatterns = [
    path("EmployeesList", views.EmployeesList, name="EmployeesList"),
    path("EmployeeDetails/<int:id>", views.EmployeeDetails, name="EmployeeDetails"),
    path("EmployeeDelete/<int:id>/", views.EmployeeDelete, name="EmployeeDelete"),
    path("EmployeeUpdate/<int:id>/", views.EmployeeUpdate, name="EmployeeUpdate"),
    path("EmployeeInsert", views.EmployeeInsert, name="EmployeeInsert"),
    path("BulkEmployeeInsert", views.BulkInsertDemo, name="BID"),
    path("NewBulkInsert", views.NewBulkInsertDemo, name="NewBulkInsert"),
    path("BulkUpdate", views.BulkUpdateDemo, name="BulkUpdate"),
    path("BulkDeleteDemo", views.BulkDeleteDemo, name="BulkDeleteDemo"),
    path("DeleteUsingRadio", views.DeleteUsingRadio, name="DeleteUsingRadio"),
    path("PageWiseEmployees", views.PageWiseEmployeesList, name="PageWiseEmployees"),
    path("cascadingselect/", views.cascadingselect, name="cascadingselect"),
    path("load_states/", views.load_states, name="load_states"),
    path("load_cities/", views.load_cities, name="load_cities"),
    path("TransactionDemo/", views.TransactionDemo, name="TransactionDemo"),
]

PayRollApp/models.py
from ast import mod
from tkinter import Widget

from django.db import models
from django.forms import CharField
from pyexpat import model


class Department(models.Model):
    DeptName = models.CharField(max_length=30)
    LocationName = models.CharField(max_length=30)

    def __str__(self) -> str:
        return self.DeptName


class Country(models.Model):
    CountryName = models.CharField(max_length=30)

    def __str__(self) -> str:
        return self.CountryName


# Create your models here.
class Employee(models.Model):
    COUNTRIES = [
        ("IND", "India"),
        ("USA", "United States of America"),
        ("UK", "United Kingdom"),
        ("AUS", "Australia"),
        ("AU", "Australia"),
        ("SP", "Spain"),
    ]

    FirstName = models.CharField(max_length=30)
    LastName = models.CharField(max_length=30)
    TitleName = models.CharField(max_length=30)
    HasPassport = models.BooleanField()
    Salary = models.IntegerField()
    BirthDate = models.DateField()
    HireDate = models.DateField()
    Notes = models.CharField(max_length=200)
    # Country = models.CharField(max_length=35, choices=COUNTRIES, default=None)
    Email = models.EmailField(default="", max_length=50)
    PhoneNumber = models.CharField(default="", max_length=20)
    EmpDepartment = models.ForeignKey(
        "Department", default=0, on_delete=models.PROTECT, related_name="Departments"
    )
    EmpCountry = models.ForeignKey(
        "Country", default=0, on_delete=models.PROTECT, related_name="Countries"
    )


class PartTimeEmployee(models.Model):
    FirstName = models.CharField(max_length=30)
    LastName = models.CharField(max_length=30)
    TitleName = models.CharField(max_length=30)


class State(models.Model):
    name = models.CharField(max_length=100, null=True)
    country = models.ForeignKey(Country, on_delete=models.PROTECT, default=None)

    def __str__(self):
        return self.name


class City(models.Model):
    name = models.CharField(max_length=100, null=True)
    state = models.ForeignKey(State, on_delete=models.PROTECT, default=None)

    def __str__(self):
        return self.name


class OnSiteEmployees(models.Model):
    first_name = models.CharField(max_length=30, null=True)
    last_name = models.CharField(max_length=30, null=True)
    country = models.ForeignKey(Country, on_delete=models.PROTECT, default=None)
    state = models.ForeignKey(State, on_delete=models.PROTECT, default=None)
    city = models.ForeignKey(City, on_delete=models.PROTECT, default=None)

    def __str__(self) -> str:
        return str(self.first_name)

PayRollApp/forms.py
from typing import Any, Mapping

from django import forms
from django.core.files.base import File
from django.db.models.base import Model
from django.forms import Select, TextInput, modelform_factory
from django.forms.utils import ErrorList

from PayRollApp.models import Employee, OnSiteEmployees, PartTimeEmployee


# Creating a Form based Model
class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = "__all__"
        widgets = {
            "BirthDate": forms.widgets.DateInput(attrs={"type": "date"}),
            "HireDate": forms.widgets.DateInput(attrs={"type": "date"}),
        }


PartTimeEmployeeForm = modelform_factory(
    PartTimeEmployee, fields=["FirstName", "LastName", "TitleName"]
)


# Form Model
class DynamicPartTimeEmployeeForm(PartTimeEmployeeForm):
    def __init__(self, *args, **kwargs) -> None:
        super(DynamicPartTimeEmployeeForm).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs.pop("required", None)


class NewPartTimeEmployeeForm(forms.ModelForm):
    class Meta:
        model = PartTimeEmployee
        fields = "__all__"


PartTimeEmployeeFormSet = forms.modelformset_factory(
    PartTimeEmployee, form=NewPartTimeEmployeeForm, extra=10
)


# Form Model
class OnSiteEmployeesForm(forms.ModelForm):
    class Meta:
        model = OnSiteEmployees
        fields = ["first_name", "last_name", "country", "state", "city"]

        widgets = {
            "first_name": TextInput(
                attrs={
                    "class": "form-control",
                    "style": "max-width: 300px;",
                    "placeholder": "First Name",
                }
            ),
            "last_name": TextInput(
                attrs={
                    "class": "form-control",
                    "style": "max-width: 300px;",
                    "placeholder": "Last Name",
                }
            ),
            "country": Select(
                attrs={
                    "class": "form-control",
                    "style": "max-width: 300px;",
                    "placeholder": "Country",
                }
            ),
            "state": Select(
                attrs={
                    "class": "form-control",
                    "style": "max-width: 300px;",
                    "placeholder": "State",
                }
            ),
            "city": Select(
                attrs={
                    "class": "form-control",
                    "style": "max-width: 300px;",
                    "placeholder": "City",
                }
            ),
        }

PayRollApp/views.py
from django.conf import settings
from django.core.paginator import PageNotAnInteger, Paginator
from django.db import transaction
from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import redirect, render

from PayRollApp.forms import (
    EmployeeForm,
    OnSiteEmployeesForm,
    PartTimeEmployeeForm,
    PartTimeEmployeeFormSet,
)
from PayRollApp.models import City, Employee, PartTimeEmployee, State


# Create your views here.
def EmployeesList(request):
    # Employees = Employee.objects.all()
    Employees = Employee.objects.select_related("EmpDepartment", "EmpCountry").all()
    # print(Employees.query)
    TemplateFileName = "PayRollApp/EmployeesList.html"
    context = {"Employees": Employees}
    return render(request, TemplateFileName, context)


def EmployeeDetails(request, id):
    # employee = Employee.objects.get(id=id)
    employee = (
        Employee.objects.select_related("EmpDepartment", "EmpCountry")
        .all()
        .filter(id=id)
    )
    TemplateFileName = "PayRollApp/EmployeeDetails.html"
    context = {"employee": employee[0]}
    return render(request, TemplateFileName, context)


def EmployeeDelete(request, id):
    # employee = Employee.objects.get(id=id)
    employee = (
        Employee.objects.select_related("EmpDepartment", "EmpCountry")
        .all()
        .filter(id=id)
    )
    TemplateFileName = "PayRollApp/EmployeeDelete.html"
    context = {"employee": employee[0]}
    if request.method == "POST":
        employee.delete()
        return redirect("EmployeesList")
    return render(request, TemplateFileName, context)


def EmployeeUpdate(request, id):
    TemplateFileName = "PayRollApp/EmployeeUpdate.html"
    # employee = Employee.objects.get(id=id)
    employee = (
        Employee.objects.select_related("EmpDepartment", "EmpCountry")
        .all()
        .filter(id=id)
    )
    form = EmployeeForm(instance=employee[0])
    context = {"form": form}
    if request.method == "POST":
        form = EmployeeForm(request.POST, instance=employee[0])
        print(f"the form is valid {form.is_valid()}")
        if form.is_valid():
            form.save()
        return redirect("EmployeesList")
    return render(request, TemplateFileName, context)


# Function based view
def EmployeeInsert(request):
    TemplateFile = "PayRollApp/EmployeeInsert.html"
    form = EmployeeForm()

    if request.method == "POST":
        form = EmployeeForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect("EmployeesList")

    return render(request, TemplateFile, {"form": form})


def BulkInsertDemo(request):
    extra_forms = 10
    forms = [
        PartTimeEmployeeForm(request.POST or None, prefix=f"employee-{i}")
        for i in range(extra_forms)
    ]
    Status = ""
    if request.method == "POST":
        for form in forms:
            if form.is_valid() and form.cleaned_data.get("FirstName", ""):
                form.save()
                Status = "Records were inserted successfully..."

    return render(
        request,
        "PayRollApp/parttimeemployee_list.html",
        {"forms": forms, "extra_forms": range(extra_forms), "Status": Status},
    )


def NewBulkInsertDemo(request):

    if request.method == "POST":
        formset = PartTimeEmployeeFormSet(request.POST, prefix="employee")
        if formset.is_valid():
            employees = formset.save(commit=False)
            PartTimeEmployee.objects.bulk_create(employees)
            return redirect("NewBulkInsert")
    else:
        formset = PartTimeEmployeeFormSet(
            queryset=PartTimeEmployee.objects.none(), prefix="employee"
        )
    return render(
        request,
        "PayRollApp/NewBulkInsert.html",
        {"formset": formset},
    )


def BulkUpdateDemo(request):
    employees = PartTimeEmployee.objects.all()
    forms = [
        PartTimeEmployeeForm(
            request.POST or None, instance=employee, prefix=f"employee-{employee.id}"
        )
        for employee in employees
    ]
    if request.method == "POST":
        updated_data = []
        for form in forms:
            if form.is_valid():
                employee = form.instance
                employee.FirstName = form.cleaned_data["FirstName"]
                employee.LastName = form.cleaned_data["LastName"]
                employee.TitleName = form.cleaned_data["TitleName"]
                updated_data.append(employee)
        PartTimeEmployee.objects.bulk_update(
            updated_data, ["FirstName", "LastName", "TitleName"]
        )

    return render(
        request,
        "PayRollApp/BulkUpdateDemo.html",
        {"forms": forms, "employees": employees},
    )


def BulkDeleteDemo(request):
    employees = PartTimeEmployee.objects.all()
    if request.method == "POST":
        if selected_ids := request.POST.getlist("selected_ids"):
            PartTimeEmployee.objects.filter(pk__in=selected_ids).delete()
            return redirect("BulkDeleteDemo")
    return render(
        request,
        "PayRollApp/BulkDelete.html",
        {"employees": employees},
    )


def DeleteUsingRadio(request):
    employees = PartTimeEmployee.objects.all()

    if request.method == "POST":
        if selected_id := request.POST.get("selected_id"):
            PartTimeEmployee.objects.filter(pk=selected_id).delete()
            return redirect("DeleteUsingRadio")

    return render(
        request,
        "PayRollApp/DeleteUsingRadio.html",
        {"employees": employees},
    )


def PageWiseEmployeesList(request):
    page_size = int(request.GET.get("page_size", getattr(settings, "PAGE_SIZE", 5)))
    page = request.GET.get("page", 1)

    search_query = request.GET.get("search", "")

    sort_by = request.GET.get("sort_by", "id")
    sort_order = request.GET.get("sort_order", "asc")

    valid_sort_fields = ["id", "FirstName", "LastName", "TitleName"]
    if sort_by not in valid_sort_fields:
        sort_by = "id"

    employees = PartTimeEmployee.objects.filter(
        Q(id__icontains=search_query)
        | Q(FirstName__icontains=search_query)
        | Q(LastName__icontains=search_query)
        | Q(TitleName__icontains=search_query)
    )
    # apply sorting
    if sort_order == "desc":
        employees.order_by(f"-{sort_by}")
    else:
        employees.order_by(f"{sort_by}")
    # employees = PartTimeEmployee.objects.all()
    pageinator = Paginator(employees, page_size)
    try:
        employees_page = pageinator.page(page)
    except PageNotAnInteger:
        employees_page = pageinator.page(1)
    return render(
        request,
        "PayRollApp/PageWiseEmployees.html",
        context={
            "employees_page": employees_page,
            "page_size": page_size,
            "search_query": search_query,
            "sort_by": sort_by,
            "sort_order": sort_order,
        },
    )


def cascadingselect(request):
    employee_form = OnSiteEmployeesForm()

    if request.method == "POST":
        employee_form = OnSiteEmployeesForm(request.POST)
        if employee_form.is_valid():
            employee_form.save()
            return JsonResponse({"success": True})
    return render(
        request, "PayRollAPp/CascadingDemo.html", {"employee_form": employee_form}
    )


def load_states(request):
    country_id = request.GET.get("country_id")
    states = State.objects.filter(country_id=country_id).values("id", "name")
    return JsonResponse(list(states), safe=False)


def load_cities(request):
    state_id = request.GET.get("state_id")
    cities = City.objects.filter(state_id=state_id).values("id", "name")
    return JsonResponse(list(cities), safe=False)


def TransactionDemo(request):
    try:
        with transaction.atomic():
            employee = PartTimeEmployee.objects.create(
                FirstName="Bob", LastName="Culbertson", TitleName="Friend"
            )
            employee = PartTimeEmployee.objects.create(
                FirstName="Shane", LastName="McQuire", TitleName="Friend"
            )
            employee = PartTimeEmployee.objects.create(
                FirstName="Bill", LastName="Verhoff", TitleName="Friend"
            )
            employee = PartTimeEmployee.objects.create(
                FirstName="Robin", LastName="Leonard", TitleName="Boxer"
            )
            employee = PartTimeEmployee.objects.create(
                FirstName="Bill", Lastame="Sweeney", TitleName="Salesman"
            )
    except Exception as e:
        return render(request, "PayRollApp/TransactionDemo.html", {"Message": str(e)})
    return render(request, "PayRollApp/TransactionDemo.html", {"Message": "Success!!!"})

PayRollApp/templates/PayRollApp/BulkDelete.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Bulk Delete Demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous" />
    <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
  </head>
  <body>
    <div class="container mt-5">
      <h2>Employee List</h2>
      <form action="" method="post">
        {% csrf_token %}
        <table class="table">
          <thead>
            <th>ID</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Title</th>
          </thead>
          <tbody>
            {% for employee in employees %}
              <tr>
                <td>{{ employee.id }}</td>
                <td>{{ employee.FirstName }}</td>
                <td>{{ employee.LastName }}</td>
                <td>{{ employee.TitleName }}</td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
        <button type="button" class="btn btn-danger" id="bulk-delete">Bulk Delete Submit</button>
      </form>
    </div>
  </body>
</html>l

PayRollApp/templates/PayRollApp/BulkUpdateDemo.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Bulk Update Demo</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" />
  </head>
  <body>
    <div class="container mt-5">
      <center>
        <h2>Edit Employee Records</h2>
      </center>
      <br />
      <form method="post">
        {% csrf_token %}

        <div class="form-row font-weight-bold">
          <div class="col-md-1 mb-3">
            <center>ID</center>
          </div>
          <div class="col-md-4 mb-3">
            <center>First Name</center>
          </div>
          <div class="col-md-4 mb-3">
            <center>Last Name</center>
          </div>
          <div class="col-md-3 mb-3">
            <center>Title</center>
          </div>
        </div>

        {% for form in forms %}
          <div class="form-row">
            <div class="col-md-1 mb-3">
              <center>{{ form.instance.id }}</center>
            </div>
            <div class="col-md-4 mb-3">
              <center>{{ form.FirstName }}</center>
            </div>
            <div class="col-md-4 mb-3">
              <center>{{ form.LastName }}</center>
            </div>
            <div class="col-md-3 mb-3">
              <center>{{ form.TitleName }}</center>
            </div>
          </div>
        {% endfor %}

        <center>
          <button type="submit" class="btn btn-primary">Submit</button>
        </center>
      </form>
    </div>
  </body>
</html>

PayRollApp/templates/PayRollApp/CascadingDemo.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Cascading Dropdown List Demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous" />
  </head>
  <body>
    <div class="container">
      <dir>
        <h1>Cascading Dropdown Lists Demo</h1>
      </dir>
      <form action="" method="POST" id="employeeForm">
        {% csrf_token %}
        {{ employee_form.as_p }}
        <button class="btn btn-primary" type="submit">Submit</button>
      </form>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
    <script>
      $(document).ready(function () {
        $('#id_state').empty()
        $('#id_city').empty()
        $('#id_country').change(function () {
          var countryId = $(this).val()
      
          $.ajax({
            url: "{% url 'load_states' %}",
            data: { country_id: countryId },
            dataType: 'json',
            success: function (data) {
              var stateSelect = $('#id_state')
              stateSelect.empty()
              $.each(data, function (key, value) {
                stateSelect.append('<option value="' + value.id + '">' + value.name + '</option>')
              })
              stateSelect.change()
            }
          })
          $('#id_state').change(function () {
            var stateId = $(this).val()
      
            $.ajax({
              url: "{% url 'load_cities' %}",
              data: { state_id: stateId },
              dataType: 'json',
              success: function (data) {
                var citySelect = $('#id_city')
                citySelect.empty()
                $.each(data, function (key, value) {
                  citySelect.append('<option value="' + value.id + '">' + value.name + '</option>')
                })
              }
            })
          })
        })
      })
    </script>
  </body>
</html>

PayRollApp/templates/PayRollApp/DeleteUsingRadio.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Delete Using Radio Button</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous" />
    <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
  </head>
  <body>
    <div class="container mt-5">
      <form action="" method="post">
        {% csrf_token %}
        <table class="table">
          <thead>
            <tr>
              <th></th>
              <th>ID</th>
              <th>First Name</th>
              <th>Last Name</th>
              <th>Title</th>
            </tr>
          </thead>
          <tbody>
            {% for employee in employees %}
              <tr>
                <td>
                  <input type="radio" name="selected_id" value="{{ employee.id }}" class="row-checkbox" />
                </td>
                <td>{{ employee.id }}</td>
                <td>{{ employee.FirstName }}</td>
                <td>{{ employee.LastName }}</td>
                <td>{{ employee.TitleName }}</td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
        <button type="button" class="btn btn-danger" id="delete-submit">Delete Submit</button>
      </form>
    </div>
    <script>
      $(document).ready(function () {
        $('#delete-submit').on('click', function () {
          var selectedId = $('input[name="selected_id"]:checked').val()
      
          if (selectedId) {
            var confirmDelete = confirm('Are you sure you want to delete the selected row?')
      
            if (confirmDelete) {
              $('form').append('<input type="hidden" name="selected_id" value="' + selectedId + '">')
              $('form').submit()
            }
          } else {
            alert('Please select a row to delete.')
          }
        })
      })
    </script>
  </body>
</html>

PayRollApp/templates/PayRollApp/EmployeeDelete.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Employee Delete</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous" />
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </head>
  <body>
    <h1>Delete Employee</h1>
    <h3>Are you sure you want to delete this?</h3>
    <table class="table">
      <tr>
        <td>Employee ID</td>
        <td>{{ employee.id }}</td>
      </tr>
      <tr>
        <td>FirstName</td>
        <td>{{ employee.FirstName }}</td>
      </tr>

      <tr>
        <td>LastName</td>
        <td>{{ employee.LastName }}</td>
      </tr>
      <tr>
        <td>HasPassport</td>
        <td>{{ employee.HasPassport }}</td>
      </tr>
      <tr>
        <td>Salary</td>
        <td>{{ employee.Salary }}</td>
      </tr>
      <tr>
        <td>BirthDate</td>
        <td>{{ employee.BirthDate }}</td>
      </tr>
      <tr>
        <td>HireDate</td>
        <td>{{ employee.HireDate }}</td>
      </tr>
      <tr>
        <td>Country</td>
        <td>{{ employee.EmpCountry.CountryName }}</td>
      </tr>
      <tr>
        <td>Notes</td>
        <td>{{ employee.Notes }}</td>
      </tr>
      <tr>
        <td>Email</td>
        <td>{{ employee.Email }}</td>
      </tr>
      <tr>
        <td>PhoneNumber</td>
        <td>{{ employee.PhoneNumber }}</td>
      </tr>
      <tr>
        <td>Department Name</td>
        <td>{{ employee.EmpDepartment.DeptName }}</td>
      </tr>
      <tr>
        <td>Location Name</td>
        <td>{{ employee.EmpDepartment.LocationName }}</td>
      </tr>
    </table>
    <form method="POST">
      {% csrf_token %}
      <div>
        <input type="submit" value="Delete" class="btn btn-danger" />|
        <a href="{% url 'EmployeesList' %}">Back To List</a>
      </div>
    </form>
  </body>
</html>

PayRollApp/templates/PayRollApp/EmployeeDetails.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Employee Details</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous" />
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </head>
  <body>
    <h1>Employee Details</h1>

    <table class="table">
      <tr>
        <td>Employee ID</td>
        <td>{{ employee.id }}</td>
      </tr>
      <tr>
        <td>FirstName</td>
        <td>{{ employee.FirstName }}</td>
      </tr>

      <tr>
        <td>LastName</td>
        <td>{{ employee.LastName }}</td>
      </tr>
      <tr>
        <td>HasPassport</td>
        <td>{{ employee.HasPassport }}</td>
      </tr>
      <tr>
        <td>Salary</td>
        <td>{{ employee.Salary }}</td>
      </tr>
      <tr>
        <td>BirthDate</td>
        <td>{{ employee.BirthDate }}</td>
      </tr>
      <tr>
        <td>HireDate</td>
        <td>{{ employee.HireDate }}</td>
      </tr>
      <tr>
        <td>Country</td>
        <td>{{ employee.EmpCountry }}</td>
      </tr>
      <tr>
        <td>Notes</td>
        <td>{{ employee.Notes }}</td>
      </tr>
      <tr>
        <td>Email</td>
        <td>{{ employee.Email }}</td>
      </tr>
      <tr>
        <td>PhoneNumber</td>
        <td>{{ employee.PhoneNumber }}</td>
      </tr>
      <tr>
        <td>Department Name</td>
        <td>{{ employee.EmpDepartment.DeptName }}</td>
      </tr>
      <tr>
        <td>Location Name</td>
        <td>{{ employee.EmpDepartment.LocationName }}</td>
      </tr>
    </table>

    <div>
      <a href="{% url 'EmployeesList' %}">Back To List</a>
    </div>
  </body>
</html>